# Generated by Django 2.0.1 on 2018-01-15 04:13

from django.db import migrations, models
import image_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_upload.models.scramble_uploaded_filename, verbose_name='Upload image')),
            ],
        ),
    ]
