# Generated by Django 2.0.1 on 2018-01-15 05:22

from django.db import migrations, models
import image_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_uploadimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_upload.models.scramble_uploaded_filename, verbose_name='Upload image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
