# Generated by Django 2.0.1 on 2018-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_auto_20180115_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='captions',
            field=models.TextField(default='', verbose_name='Description of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
    ]
