# Generated by Django 2.0.1 on 2018-01-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_auto_20180115_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(default='Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
    ]
