# Generated by Django 2.0.3 on 2018-03-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0005_auto_20180115_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='captions',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='caption1',
            field=models.TextField(default='', verbose_name='Caption of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='caption2',
            field=models.TextField(default='', verbose_name='Caption of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='caption3',
            field=models.TextField(default='', verbose_name='Caption of the uploaded image'),
        ),
    ]
